minor: add automation for version (#45)
* minor: add automation for version
* add: semvercheck helper
* move the semver check to workflow

---------

Signed-off-by: Pat  <pat@calyptia.com>

diff --git a/.github/workflows/cron-sync-core.yaml b/.github/workflows/cron-sync-core.yaml
--- a/.github/workflows/cron-sync-core.yaml
+++ b/.github/workflows/cron-sync-core.yaml
@@ -28,8 +28,19 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.CI_PAT }}
 
       # Note we assume a simple version update so no chart version update
-      - run: |
-          sed -i "s/^appVersion.*$/appVersion: $NEW_CALYPTIA_CORE_VERSION/g" ./charts/core/Chart.yaml
+      - name: Run the sed on the chart file
+        run: |
+          if [[ "$NEW_CALYPTIA_CORE_VERSION" =~ ^v?([0-9]+\.[0-9]+\.[0-9]+)$ ]] ; then
+              NEW_CALYPTIA_CORE_VERSION=${BASH_REMATCH[1]}
+              echo "Valid version string: $NEW_CALYPTIA_CORE_VERSION"
+          else
+              echo "ERROR: Invalid semver string: $NEW_CALYPTIA_CORE_VERSION"
+              exit 1
+          fi
+          sed -i "s/^version.*$/version: $NEW_CALYPTIA_CORE_VERSION/g" ./charts/core/Chart.yaml
+          sed -i "s/^appVersion.*$/appVersion: v$NEW_CALYPTIA_CORE_VERSION/g" ./charts/core/Chart.yaml
+          echo "chart version=$NEW_CALYPTIA_CORE_VERSION" >> $GITHUB_OUTPUT
+          echo "app version=v$NEW_CALYPTIA_CORE_VERSION" >> $GITHUB_OUTPUT
         env:
           NEW_CALYPTIA_CORE_VERSION: ${{ steps.get-core-release.outputs.tag }}
         shell: bash
